//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NijatPortfolioEntities : DbContext
    {
        public NijatPortfolioEntities()
            : base("name=NijatPortfolioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutMe> AboutMes { get; set; }
        public virtual DbSet<AdditionalInfo> AdditionalInfoes { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<MyWorksOnProject> MyWorksOnProjects { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Technology> Technologies { get; set; }
        public virtual DbSet<UserMessage> UserMessages { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
    }
}
